use DB_Interview;

CREATE TABLE TB_COMPANY(
	CL_ID			 INT		 NOT NULL IDENTITY(1,1),
	CL_NAME			 VARCHAR(50) NOT NULL,
	CL_CONTACTSTATUS VARCHAR(20) NOT NULL,
	PRIMARY KEY (CL_ID)
);

CREATE TABLE TB_USERS(
	CL_ID			INT			NOT NULL IDENTITY(1,1),
	CL_NAME			VARCHAR(50) NOT NULL,
	CL_LOGIN		VARCHAR(50) NOT NULL,
	CL_PASSWORD		VARCHAR(50) NOT NULL,
	CL_IdCOMPANY	INT			NOT NULL references TB_COMPANY(CL_ID),
	PRIMARY KEY (CL_ID)
);
